# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: g:/source/board/cnn_vivado/cnn_vivado.srcs/sources_1/bd/design_1/ip/design_1_Conv_0_1/design_1_Conv_0_1.xci
# IP: The module: 'design_1_Conv_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/source/board/cnn_vivado/cnn_vivado.gen/sources_1/bd/design_1/ip/design_1_Conv_0_1/constraints/Conv_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_Conv_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: g:/source/board/cnn_vivado/cnn_vivado.srcs/sources_1/bd/design_1/ip/design_1_Conv_0_1/design_1_Conv_0_1.xci
# IP: The module: 'design_1_Conv_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/source/board/cnn_vivado/cnn_vivado.gen/sources_1/bd/design_1/ip/design_1_Conv_0_1/constraints/Conv_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_Conv_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
